### ISSUE TITLE
Kopf -> cerebro

### ISSUE THREAD

**Issue by rocbr** [dzharii/awesome-elasticsearch#24]
Kopf is no longer maintained. A replacement(cerebro) has been developed and is currently maintained at https://github.com/lmenezes/cerebro

**Comment by dzharii** [comment]
Hi @rocbr, I agree. 
Would you like to update the list via PR (from your branch) or 
would you like me to update the list?

I would rather keep both, since kof works well **as a plugin** on 2.x and I would put celebro on top

**Comment by rocbr** [comment]
Hi Zharii,

Thanks for your attention. I agree with you about keeping both.

Please update the list because I do not know how to do it.

Thanks !

**Comment by dzharii** [comment]
I have added the item. Thank you @rocbr
