### ISSUE TITLE
Sling, a new command line

### ISSUE THREAD

**Issue by lfroment-datasweet** [dzharii/awesome-elasticsearch#65]
Hi dzharii,

the Datasweet team (Kibana Datasweet Formula) has realeased a first version of Sling,  a collection of elasticsearch command line tools, with query based filtering capabilities.

Among the featured capabilities, Sling allows its users to ingest big datasets from files (currently supporting CSV) with a pretty straightforward method. 

Dumping, deleting can be performed using a filtering query.

https://github.com/datasweet/sling-binaries

Would you be kind enough to test it, and maybe add it to your list of useful stuff around Elastisearch?

Best regard,

Lionel

**Comment by dzharii** [comment]
Hi @lfroment-datasweet, nope sorry 
I am not going to add a link to some unknown binary files and I am not going to test this on my machine. This is a security concern. Make this project **opensource** and feel free to send a pull request to this list.
