### ISSUE TITLE
Elasticsearch Python ORM

### ISSUE THREAD

**Issue by wallneradam** [dzharii/awesome-elasticsearch#84]
Hi, I have written an ElasticSearch ORM for Python based on Pydantic. It is full Async, everything is type annotated, and very easy to use.
If you interested, I would be very happy if you could list it: https://github.com/wallneradam/esorm

**Comment by dzharii** [comment]
Hi @wallneradam
How this list works: 
to add a link with its description to the README.md, create a pull request including your changes.

I believe now you could do a quick pull request by using github's build-in editor:  
![image](https://github.com/dzharii/awesome-elasticsearch/assets/36020/f5178e84-0d03-46fb-a425-ff3c4378dda9)

Really nice project. I like the documentation and clean code with type annotations. Thank you for your effort. 
I'm closing this issue now. Looking forward to your pull request – excited to see your contribution!
